## <strong>4. NumPy: Universal Functions (UFunc)</strong>

In [1]:
import numpy as np

In [2]:
# 역수 계산 함수
def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output

# 함수 테스트
values = np.random.randint(1, 10, size=5)
print(values)
print(compute_reciprocals(values))

[7 3 2 4 3]
[0.14285714 0.33333333 0.5        0.25       0.33333333]


#### <strong>역수 계산: Python loop vs NumPy ufuncs</strong>
+ ```%timeit```: 셀 단위 코드 실행 시간을 측정하는 매직 함수

In [ ]:
# [+] 백만 개 크기의 난수 배열 생성: 정수, 값 범위 [1포함, 100포함 x) -> 1~99
big_array =np.random.randint(1, 100, size = 1000000)



In [ ]:
%%timeit   #파이썬 문법 아님 주피터 문법 %% 매직함수

# [+] Python loop를 통한 역수 계산 
compute_reciprocals(big_array)


1.34 s ± 200 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [12]:
%%timeit

# [+] NumPy ufunc을 통한 벡터화된 역수 계산
1 / big_array


2.88 ms ± 93.7 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


#### <strong>유니버설 함수들</strong>

In [13]:
# 난수 배열 2개 생성
np.random.seed(1)
arr1 = np.random.randint(10, size=5)
arr2 = np.random.randint(10, size=5)

print(arr1, arr2)

[5 8 9 5 0] [0 1 7 6 9]


In [14]:
# 배열-스칼라 연산
arr1 = arr1 - 2
print(arr1)

[ 3  6  7  3 -2]


In [15]:
# 배열-배열 연산
arr3 = arr1 + arr2
print(arr3)

[ 3  7 14  9  7]


In [17]:
# 다차원 배열 연산: 2차원 배열 ** 스칼라
arr4 = np.random.randint(10, size=(3, 5))
print(arr4)

arr5 = arr4 ** 2
print(arr5)

[[9 7 6 9 1]
 [0 1 8 8 3]
 [9 8 7 3 6]]
[[81 49 36 81  1]
 [ 0  1 64 64  9]
 [81 64 49  9 36]]


In [ ]:
"""
    UFuncs: 산술 연산
"""

# 기본 산술 연산
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x ** 2 =", x ** )

# [+] 산술 연산에 대응하는 유니버설 함수
print("x + 5 =", np.add(x, 5))
print("x - 5 =", np.subtract(x, 5))
print("x * 2 =", np.multiply(x, 2))
print("x / 2 =", np.divide(x, 2))
print("x ** 2 =", np.power(x, 2))


x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x ** 2 = [0 1 4 9]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x ** 2 = [0 1 4 9]


In [23]:
"""
    UFuncs: 절댓값 계산
"""

# [+] 절댓값 함수
x = np.array([-2, -1, 0, 1, 2])
np.abs(x)

array([2, 1, 0, 1, 2])

In [27]:
"""
    np.linspace(start, stop, num): 선형 간격 벡터 생성
        - start: 벡터의 시작 값
        - end: 벡터의 종료 값
        - num: 생성할 값의 개수
"""

# [+][0, 100]의 범위를 가지며, 균일한 간격의 5개의 값들로 구성되는 벡터를 생성
x = np.linspace(0, 100, 5)
x

array([  0.,  25.,  50.,  75., 100.])

In [56]:
# [+] [0, 100]의 범위를 가지며, [0, 10, 20, 30, ..., 100]와
# 같은 값들로 구성되는 벡터를 생성
x = np.linspace(0, 100, 11)
x

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [57]:
# 삼각함수(trigonometric functions)
theta = np.linspace(0, np.pi, 3)

print(theta)
print(np.sin(theta))
print(np.cos(theta))
print(np.tan(theta))

[0.         1.57079633 3.14159265]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [58]:
"""
    집계 함수: reduce()
"""

# 배열 생성
x = np.arange(1, 5)
x

array([1, 2, 3, 4])

In [59]:
# [+] 덧셈 연산으로 집계
aggr = np.add.reduce(x)
aggr

10

In [61]:
# [+] 곱셈 연산으로 집계
aggr = np.multiply.reduce(x)
aggr

24

In [62]:
"""
    집계 함수: accumulate()
"""

# [+] 덧셈 연산으로 집계
accum = np.add.accumulate(x)
accum

array([ 1,  3,  6, 10])

In [64]:
# [+] 곱셈 연산으로 집계
accum = np.multiply.accumulate(x)
accum

array([ 1,  2,  6, 24])

In [75]:
# 집계 함수: sum()
np.random.seed(3)
arr = np.random.rand(100000) # [+] 0~1 사이의 실수 형태의 난수 배열 생성 값이 정해저 있음 스타트 값 x

print(arr)
print("sum =", np.sum(arr))

[0.5507979  0.70814782 0.29090474 ... 0.12599742 0.94189543 0.89025983]
sum = 50103.284993937086


In [76]:
# sum(): Python 내장함수
%timeit sum(arr)

9.15 ms ± 556 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [77]:
# np.sum()
%timeit np.sum(arr) # 1000µs = 1ms

43.4 μs ± 4.18 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [100]:
# [+] 그 외의 집계함수
print("max =", np.max(arr))
print("min =", np.min(arr))
print("mean =", np.mean(arr))
print("median =", np.median(arr))
print("percentile =", np.percentile(arr))
print("variance =", np.var(arr))
print("standard deviation =", np.atd(arr))
print("index of maximum value =", np.argmax(arr))
print("index of minimum value =", np.argmin(arr))
print("Is there any number greater than 1? =", np.any(arr > 1)) #1개이상 존재하면 true 아니면 f
print("Is every number greater than 0? =", np.all(arr > 0)) 

max = 9
min = 0
mean = 4.5
median = 4.5


TypeError: percentile() missing 1 required positional argument: 'q'

In [94]:
"""다차원 집계"""

# 2차원 난수 배열 생성
np.random.seed(0)
arr = np.random.randint(10, size=(3, 4))
arr

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [96]:
# [+] 행 방향으로 집계 (row sum)
np.sum(arr, axis = 0)

array([14, 13, 13, 14])

In [97]:
# [+] 열 방향으로 집계 (column sum)
np.sum(arr, axis = 1)

array([11, 24, 19])